development:
  adapter: postgresql
  encoding: unicode
  database: sonicpi_collaboration_dev
  host: localhost
  pool: 5
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  database: sonicpi_collaboration_test
  host: localhost
  pool: 5
  min_messages: warning
